#!/bin/bash

# script to run scraper on a set of test articles and check results
# against expected data

set -e
# the command to invoke to scrape
scrape="scrapetool"

# command to compare scrape output against .expected files
compare=./compare
# set COMPARE_FLAGS to alter the checks
# eg for just headlines:
# $ export COMPARE_FLAGS="-c content"
if [ -z "$1" ]
then
    # default - scan data dir
    inputs=$(find data -iname "*.expected")
elif [ -d "$1" ]; then
    # param is an alternative directory to scan
    inputs=$(find "$1" -iname "*.expected")
else
    # param is an individual .expected file to run
    inputs="$1"
fi

goodcnt=0
badcnt=0
errcnt=0
for expected in $inputs; do
    # look for input file - either .warc or .html
    srcfile=$(echo $expected | sed 's/\.expected$/\.warc/')
    if [[ ! -f $srcfile ]]; then
        srcfile=$(echo $expected | sed 's/\.expected$/\.html/')
    fi
    tmpfile=$(mktemp)
    #echo >&2 $srcfile
    ${scrape} "file://$(pwd)/$srcfile" >$tmpfile

    set +e
    errs=$(${compare} ${COMPARE_FLAGS} $tmpfile $expected)
    result=$?
    if [ $result -eq 0 ]; then
        echo "GOOD: ${srcfile}"
        let goodcnt=goodcnt+1
    elif [ $result -eq 1 ]; then
        echo "BAD: ${srcfile}"
        echo "$errs"
        let badcnt=badcnt+1
    else
        echo "ERROR: ${srcfile}"
        echo "$errs"
        let errcnt=errcnt+1
    fi
    set -e
    rm $tmpfile
done

echo "${goodcnt} good, ${badcnt} bad, ${errcnt} errors"
